demo/demo/urls.py
from django.contrib import admin
from django.urls import path,include
from main_app import views


urlpatterns = [
    path('options/', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('', views.welcome, name='welcome'),
]

demo/main_app/urls.py
from django.urls import path
#to show which thing to view need to import views
from main_app import views

app_name = 'main_app'

urlpatterns = [
    path('demo/', views.demo_from, name='demo_form'),
    path('signup/', views.sign_up, name='sign_up'),
    path('currentusers/', views.current_users, name='current_users'),
    path('registration/', views.registration_form, name='registration_form'),
    path('login/', views.login_form, name = 'login_form'),
    path('logout/', views.logout_page, name='logout_page'),
]

demo/main_app/models.py
from django.db import models

#to use the django's bultin authentication User need to import this
from django.contrib.auth.models import User



# Create your models here.

#the following model is for a normal user database
class Users(models.Model):
    first_name = models.CharField(max_length=32, null = False)
    last_name = models.CharField(max_length=32, null = False)
    email = models.EmailField(max_length=64, unique=True, null = False)
    url = models.URLField(max_length=128, null = True)
    # password

    def __str__(self):
        return self.first_name


#this model is to register user in the django's builtin Model User
#and make the one to one relationship with that models

class UserProfileInfo(models.Model):
    #HERE IS the main part
    #setting up this model with User model with one to one relationship
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #for some additional info specific for this models
    profile_pic = models.ImageField(upload_to='main_app/profile_pics', blank=True)
    #to working with picture we need a package
    # pip install pillow to use this!
    #if this command failed to execute then run the following
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    portfolio_site = models.URLField(blank=True)
    #blank means we can entry empty values in the databases


    #to return the name of this class we return the user name of this class
    def __str__(self):
        return self.user.username

demo/main_app/forms.py
from django import forms
#to check validation both builtin and custom neeed to call a package
from django.core import validators
#to crete exact like a model importing models
from main_app.models import Users,UserProfileInfo
#to use the django's buitin model class User
from django.contrib.auth.models import User


#the following fucntion is a example of custom validation
def is_first_letter_is_capital_and_alphabet(value):
    #WE Know the achi integer valuse of capital alphabets is from 65 to 90
    #converting the first letter of the input to ascii integer
    #fucntion ord('Letter') returns the ascii integer value
    asci_integer_of_first = ord(value[0])
    print(asci_integer_of_first)
    if asci_integer_of_first < 65 or asci_integer_of_first > 90:
        raise forms.ValidationError("Nmae should be start with capital and alphabet!")



class Demo_form(forms.Form):
    # here we are giving attrs fields for styling in html with bootstrapcss
    name = forms.CharField(max_length=64, label='Full Name', validators = [is_first_letter_is_capital_and_alphabet], #using the custom validation method
                                                    widget = forms.TextInput(attrs={
                                                    'placeholder' : 'Your full Name!',
                                                    }))
    email = forms.EmailField(max_length=128, widget = forms.EmailInput(attrs={
                                                        'placeholder' : 'Enter your email address here',
                                                        }))

    verify_email = forms.EmailField(max_length=128, label = 'Verify Email', widget = forms.EmailInput(attrs={
                                                        'placeholder' : 'Enter your email address again!',
                                                        }))

    phone = forms.CharField(max_length=32, required = False, widget = forms.TextInput(attrs={
                                                                        'placeholder' : 'Your Phone Number',
                                                                        }))
    bot_catcher = forms.CharField(required = False, widget = forms.HiddenInput, validators = [validators.MaxLengthValidator(0)]) #calling django's builtin validators

    def clean(self):
        all_cleaned_data = super().clean()
        name = all_cleaned_data.get('name')
        print(name)
        email = all_cleaned_data['email']
        print(email)
        vmail = all_cleaned_data['verify_email']
        print(vmail)

        if email != vmail:
            # two ways to make validation error
            #following one is field specific
            self.add_error('verify_email', "Make sure the emails are same!")

            # raise forms.ValidationError("Make sure the emails are same")
            #
            #
            #as we are using crispy forms and bootstrap so skipping this one
            #this still works but wont be displayed in page.
        else:
            print("emails matched")

        return None


class User_Form(forms.ModelForm):

    class Meta():
        # very important note in this Meta class we must assign Users(model) in side of model variable, other wise it won't work
        model = Users
        fields = '__all__'


    #here creatint new attributes of this form and overriding the model's attribute
    first_name = forms.CharField(max_length=32, validators = [is_first_letter_is_capital_and_alphabet], widget = forms.TextInput(attrs = {'placeholder':"Enter your first name"}))
    last_name = forms.CharField(max_length=32, validators = [is_first_letter_is_capital_and_alphabet], widget = forms.TextInput(attrs = {'placeholder':"Enter your last name"}))
    bot_catcher = forms.CharField(widget=forms.HiddenInput, required = False, validators = [validators.MaxLengthValidator(0)])
    email = forms.EmailField(max_length=64, widget=forms.EmailInput(attrs={'placeholder':'Enter mail address here'}))
    verify_email = forms.EmailField(max_length=64, label = 'Verify Email', widget=forms.EmailInput(attrs={'placeholder':'Enter your email address again!!'}))
    url = forms.URLField(max_length=128, required = False, widget = forms.URLInput(attrs = {"placeholder":"Website(optional)"}))

    def clean(self):
        all_cleaned_data = super().clean()
        email = all_cleaned_data['email']
        vmail = all_cleaned_data['verify_email']

        if email != vmail:
            self.add_error('verify_email', "Make sure the emails are same!")

        else:
            print("emails matched")

        return None

#here we will manipulate the django's builtin user form
#so that we need to import the model class User from django.auth.contrib.models
class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

    #modifying the field of password attribute
    password = forms.CharField(widget=forms.PasswordInput())

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

demo/main_app/views.py
from django.shortcuts import render
# to using the forms we have to import them in the views.py file
from main_app import forms
from main_app.models import Users
from main_app.forms import User_Form, UserForm, UserProfileInfoForm

#additional imports for the login and logout capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def demo_from(request):
    form = forms.Demo_form()

    if request.method == 'POST':
        form = forms.Demo_form(request.POST)

        if form.is_valid():
            print("Validation success")
            print(form.cleaned_data['name'])



    return render(request, 'main_app/demo_form.html', {'form':form})
    #we are passing here the context (last argument) so that we can use template tagging in the html file

def welcome(request):

    return render(request, 'main_app/welcome.html', {'for_custom':'Custom Filters checking!!'})

def sign_up(request):
    form = forms.User_Form()

    if request.method == "POST":
        form = forms.User_Form(request.POST)

        if form.is_valid():
            print("validation success of user form success")
            form.save(commit=True)
            print('Saved to databse!!')
            return current_users(request)
        else:
            print("validation error")

    return render(request, 'main_app/sign_up.html', {'form':form})

def current_users(request):
    user_list = Users.objects.order_by('first_name')

    return render(request, 'main_app/current_users.html', {"user": user_list})



def registration_form(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            #any csv,pdf,pic,are in returned with request.Files
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'main_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def login_form(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('welcome'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'main_app/login.html', {})


@login_required
def logout_page(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('welcome'))

demo/templates/main_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    {% block head_block %}

    {% endblock %}

  </head>
  <body>
    <div>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'welcome' %}">Welcome</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'main_app:sign_up' %}">Sign Up<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'main_app:current_users' %}">Current Users</a>
            <a class="nav-item nav-link" href="{% url 'main_app:demo_form' %}">Demo</a>
            <a class="nav-item nav-link" href="{% url 'main_app:registration_form' %}">User Registration</a>

            {# set the logic to show login or logout button #}
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'main_app:logout_page' %}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'main_app:login_form' %}">Login</a>
            {% endif %}  
            <a class="nav-item nav-link disabled" href="#">Disabled</a>
          </div>
        </div>
      </nav>
    </div>
<!-- this navbar is default in every page...now using the body block so that the following won't be inherited -->

    <div class="container">
      {% block body_block %}
        <!-- in this block the code is specific for this html page...it won't be inherited -->

      {% endblock %}
    </div>





    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

demo/templates/main_app/current_users.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
  {% block head_block %}
  <link rel="stylesheet" href="{% static 'css/current_users.css' %}">

  {% endblock %}

  {% block body_block %}
  <h1>Current Users of our community! :)</h1>

  {% if user %}
  <div class="jumbotron">
    <ol>
      {% for person in user %}
      <li id="top_point">User Info</li>
        <ul>
          <li>Name: <span id="inside">{{ person.first_name }} {{ person.last_name}}</span></li>
          <li>Email: <span id="inside">{{ person.email }}</span></li>
          <li id="url" >Url: {{ person.url }}</li>
        </ul>
      {% endfor %}

    </ol>
      {% else %}
        <p>Sorry! No Existing Users!</p>
      {% endif %}


  </div>
  {% endblock %}

demo/templates/main_app/demo_form.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
{% load crispy_forms_tags %}
  {% block body_block %}

    <form method="post">
        {% csrf_token %}
        <!-- for Cross Site Request Forgery -->
        <div class="form-group">
          {{ form.name|as_crispy_field }}
        </div>
        <div class="form-group">
          {{ form.email|as_crispy_field }}
        </div>
        <div class="form-group">
          {{ form.verify_email|as_crispy_field }}
        </div>
        <div class="form-group">
          {{ form.phone|as_crispy_field }}
        </div>

        <div class="checkbox">
          <label><input type="checkbox"> Remember me</label>
        </div>
        <div class="form-group">
          {{ form.bot_catcher|as_crispy_field }}
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    {% endblock %}

demo/templates/main_app/login.html
{% extends 'main_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'main_app:login_form' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

demo/templates/main_app/registration.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}
{% load crispy_forms_tags %}
  {% block body_block %}
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for Registering!</h1>
      {% else %}
          <h1>Register Here</h1>
          <h2>Fill out the forms below</h2>
          <form enctype="multipart/form-data" method="post">
              {% csrf_token %}
              <!-- for Cross Site Request Forgery -->
              <div class="form-group">
                {{ user_form.username|as_crispy_field }}
              </div>
              <div class="form-group">
                {{ user_form.email|as_crispy_field }}
              </div>
              <div class="form-group">
                {{ user_form.password|as_crispy_field }}
              </div>
              <div class="form-group">
                {{ profile_form.portfolio_site|as_crispy_field }}
              </div>

              <div class="form-group">
                {{ profile_form.profile_pic|as_crispy_field }}
              </div>

              <button type="submit" class="btn btn-default">Submit</button>
            </form>
          {%  endif %}

    </div>


   {% endblock %}

demo/templates/main_app/sign_up.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}
{% load crispy_forms_tags %}
  {% block body_block %}

  <h1>Please sign up,</h1>
  <form method="post">
      {% csrf_token %}
      <!-- for Cross Site Request Forgery -->
      <div class="form-group">
        {{ form.first_name|as_crispy_field }}
      </div>
      <div class="form-group">
        {{ form.last_name|as_crispy_field }}
      </div>
      <div class="form-group">
        {{ form.email|as_crispy_field }}
      </div>
      <div class="form-group">
        {{ form.verify_email|as_crispy_field }}
      </div>

      <!-- <div class="form-group">
        for password
      </div> -->

      <div class="form-group">
        {{ form.url|as_crispy_field }}
      </div>

      <div class="form-group">
        {{ form.bot_catcher|as_crispy_field }}
      </div>


      <button type="submit" class="btn btn-default">Submit</button>
    </form>



  {% endblock %}

demo/templates/main_app/welcome.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
{% load extra_template_filters %}
  {% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the Demo Project!</h1>

  </div>
  <p>Thank you for visiting our web application. Currently this site is under being developed. But we can still sign up to get the latest news when we launch our fully functional website.Here is a link to the sign up page-</p>
  <ul>
    <li><a href="{% url 'main_app:sign_up' %}">Sign up</a></li>
  </ul>
  <p>Checking custom filters. If worked, the next line will be <span style="color:orangered">'Custom Filters (checking to)Checked!!</span>'</p>
  {{ for_custom|custom:'checking' }}
  {%  if user.is_authenticated %}
    <h2>Signed in as {{ user.username }}</h2>
  {% endif %} 
  {% endblock %}